### PR TITLE
add multi faces supported

### PR DESCRIPTION
**Pull request by warmshao**
Support for multiple faces in the source image, some results:

https://github.com/KwaiVGI/LivePortrait/assets/138360003/b37de35d-6feb-4100-b73f-58ac23121483

https://github.com/KwaiVGI/LivePortrait/assets/138360003/c0c8de4f-6a6f-43fa-89f9-168ff3f150ef

### CODE REVIEW

**Comment by FurkanGozukara** [comment]
Haha looking cool

**Comment by cleardusk** [comment]
Thanks for your PR. The demo looks so funny.

But we will carefully re-think the design and structure of this repo for supporting new features. For example, will the multi-face feature conflict with video-editing?

Keep the discussion going : )

**Comment by Inferencer** [comment]
[arcface](https://github.com/deepinsight/insightface?tab=readme-ov-file#arcface-video-demo) for multi-face detection would be a suitable choice as you can compare if two faces are similar or not
68747470733a2f2f696e7369676874666163652e61692f6173736574732f696d672f6769746875622f666163657265636f676e6974696f6e66726f6d766964656f2e504e47

**Comment by warmshao** [comment]
> [arcface](https://github.com/deepinsight/insightface?tab=readme-ov-file#arcface-video-demo) for multi-face detection would be a suitable choice as you can compare if two faces are similar or not 68747470733a2f2f696e7369676874666163652e61692f6173736574732f696d672f6769746875622f666163657265636f676e6974696f6e66726f6d766964656f2e504e47

You reminded me that Friends is one of my favorite TV shows, so I found a photo from Friends and ran the model. 

https://github.com/user-attachments/assets/7995a06d-5c4d-4ceb-9d2a-f90b70467c68

haha, interesting

**Comment by FurkanGozukara** [comment]
@warmshao how can we use this right now? it is not on the interface?

**Pull request closed without merging**
