### PR TITLE
docs：Add Chinese document for readme

### PR DESCRIPTION
**Pull request by sam9029**
Add Chinese document for readme, request merge🤓

### CODE REVIEW

**Comment by cleardusk** [comment]
Thanks. Interesting, we will review it tommorrow. @sam9029

**Comment by cleardusk** [comment]
“嬉皮笑脸平台(Huggingface)”  这个是机翻的嘛😂 @sam9029

**Comment by sam9029** [comment]
> “嬉皮笑脸平台(Huggingface)” 这个是机翻的嘛😂 @sam9029

嘿嘿，我看logo直译的

**Comment by sam9029** [comment]
im happy，it's great. 🎉🎉

**Comment by cleardusk** [comment]
@sam9029 If the changelogs could be translated into Chinese, that would be very GREAT! 🤗

**Pull request merged**
