### PR TITLE
Check for ffmpeg

### PR DESCRIPTION
**Pull request by wagenrace**
If you try to run the inference without ffmpeg installed you get the error "File Not Found"

This is not very clear, so this PR just adds a test to make sure ffmpeg is installed before running

Also add the ffmpeg instruction to the read

### CODE REVIEW

**Comment by cleardusk** [comment]
Great thanks for your PR!

It seems the PR has conflict, could you please rebase the newest main branch, and rename the function to, e.g., `fast_check_ffmpeg`? 💖 @wagenrace

**Comment by wagenrace** [comment]
@cleardusk done! Thanks for the feedback

**Comment by cleardusk** [comment]
Thanks, we prefer to merge it tomorrow. Another small advice, the code is not formatted in lines, e.g., L15, L38  : )

**Comment by wagenrace** [comment]
Sure, let me look at it. What formater do you use? 
I cannot find it in the readme

**Comment by cleardusk** [comment]
I just use the standard formatter within VScode. In this PR, just keeping the blank lines equal is OK.

You have reminded me and I will consider using a format config lately. : )

**Pull request merged**
