### PR TITLE
Update install documentation (for windows)

### PR DESCRIPTION
**Pull request by GermanBluefox**
under windows I get message run "init" before "activate"

### CODE REVIEW

**Review by pg56714 — APPROVED** [review]

**Comment by cleardusk** [comment]
Thanks @GermanBluefox, we will check it tommorrow.

**Comment by zzzweakman** [comment]
@GermanBluefox Thanks for your PR. From my understanding, the init command is only required the first time a user installs conda. Did you happen to encounter this issue just after installing it?

**Review by pg56714 — CHANGES_REQUESTED** [review]
After seeing @zzzweakman's comment, I realized I shouldn't have approved this code because conda init isn't necessary. The reason is that @GermanBluefox did not create a new environment.

This PR can be directly closed.

**Comment by cleardusk** [comment]
We still appreciate your attention and active contributions. @pg56714

**Pull request closed without merging**
