### PR TITLE
fix: compile on v100

### PR DESCRIPTION
**Pull request by iloveOREO**

### CODE REVIEW

**Comment by FurkanGozukara** [comment]
how is this fixing run speed can you elaborate more?

**Comment by zzzweakman** [comment]
Thank you for the PR. Could you please provide some examples of warnings or errors that occur without setting `torch._dynamo.config.suppress_errors = True`? This would help us better understand the impact of this change. @iloveOREO 

It appears that this fix may not enhance the running speed but could potentially improve robustness. @FurkanGozukara

**Comment by iloveOREO** [comment]
without ```torch._dynamo.config.suppress_errors = True```, run speed.py failed with traceback as blow.
```
Warm up start!
Traceback (most recent call last):
  File "/data2/fengfusen/project/LivePortrait/speed.py", line 195, in <module>
    main()
  File "/data2/fengfusen/project/LivePortrait/speed.py", line 185, in main
    warm_up_models(compiled_models, stitching_retargeting_module, inputs)
  File "/data2/fengfusen/project/LivePortrait/speed.py", line 91, in warm_up_models
    compiled_models['Motion Extractor'](inputs['source_image'])
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 676, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1036, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 500, in transform
    tracer.run()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2149, in run
    super().run()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2268, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 991, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1168, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1241, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1222, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/__init__.py", line 1729, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1102, in compile_fx
    return compile_fx(
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1330, in compile_fx
    return aot_autograd(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 58, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 903, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 628, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 443, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 648, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 119, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1257, in fw_compiler_base
    return inner_compile(
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 438, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 698, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/graph.py", line 612, in run
    return super().run(*args)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/interpreter.py", line 145, in run
    self.env[node] = self.run_node(node)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/graph.py", line 957, in run_node
    result = super().run_node(n)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/interpreter.py", line 202, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/graph.py", line 819, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/graph.py", line 816, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/lowering.py", line 296, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/kernel/mm.py", line 158, in tuned_mm
    return autotune_select_algorithm("mm", choices, [mat1, mat2], layout)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/select_algorithm.py", line 1146, in autotune_select_algorithm
    return _ALGORITHM_SELECTOR_CACHE(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/select_algorithm.py", line 896, in __call__
    timings = self.lookup(
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 296, in lookup
    timings = benchmark(choices)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/select_algorithm.py", line 887, in autotune
    return make_benchmark_fn()(choices)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/select_algorithm.py", line 997, in benchmark_in_current_process
    timing = benchmark_choice_in_current_process(choice)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/select_algorithm.py", line 987, in benchmark_choice_in_current_process
    result = choice.benchmark(*example_inputs, out=out)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/select_algorithm.py", line 687, in benchmark
    return self.bmreq.benchmark(*args, output_tensor=out)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/autotune_process.py", line 455, in benchmark
    out = do_bench(fn)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/utils.py", line 170, in do_bench
    return triton_do_bench(*args, **kwargs)[0]
  File "/opt/conda/lib/python3.10/site-packages/triton/testing.py", line 102, in do_bench
    fn()
  File "/opt/conda/lib/python3.10/site-packages/triton/runtime/jit.py", line 416, in run
    self.cache[device][key] = compile(
  File "/opt/conda/lib/python3.10/site-packages/triton/compiler/compiler.py", line 193, in compile
    next_module = compile_ir(module, metadata)
  File "/opt/conda/lib/python3.10/site-packages/triton/compiler/backends/cuda.py", line 199, in <lambda>
    stages["llir"] = lambda src, metadata: self.make_llir(src, metadata, options, self.capability)
  File "/opt/conda/lib/python3.10/site-packages/triton/compiler/backends/cuda.py", line 173, in make_llir
    ret = translate_triton_gpu_to_llvmir(src, capability, tma_infos, runtime.TARGET.NVVM)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: IndexError: map::at
  target: aten.mm.default
  args[0]: TensorBox(
    View(
      StorageBox(
        ComputedBuffer(name='buf10', layout=FixedLayout('cuda', torch.float16, size=[1, 64, 64, 96], stride=[393216, 6144, 96, 1]), data=Pointwise(
          'cuda',
          torch.float16,
          def inner_fn(index):
              _, i1, i2, i3 = index
              tmp0 = ops.load(buf6, i3 + 96 * i2 + 6144 * i1)
              tmp1 = ops.load(arg83_1, i3)
              tmp2 = tmp0 + tmp1
              tmp3 = ops.to_dtype(tmp2, torch.float32, src_dtype=torch.float16)
              tmp4 = ops.load(buf7, i2 + 64 * i1)
              tmp5 = tmp3 - tmp4
              tmp6 = ops.load(buf8, i2 + 64 * i1)
              tmp7 = ops.constant(0, torch.float32)
              tmp8 = ops.constant(96, torch.float32)
              tmp9 = ops.constant(0, torch.float32)
              tmp10 = tmp8 - tmp7
              tmp11 = ops.maximum(tmp9, tmp10)
              tmp12 = tmp6 / tmp11
              tmp13 = ops.constant(1e-06, torch.float32)
              tmp14 = tmp12 + tmp13
              tmp15 = ops.rsqrt(tmp14)
              tmp16 = tmp5 * tmp15
              tmp17 = ops.load(arg2_1, i3)
              tmp18 = ops.to_dtype(tmp17, torch.float32, src_dtype=torch.float16)
              tmp19 = tmp16 * tmp18
              tmp20 = ops.load(arg3_1, i3)
              tmp21 = ops.to_dtype(tmp20, torch.float32, src_dtype=torch.float16)
              tmp22 = tmp19 + tmp21
              tmp23 = ops.to_dtype(tmp22, torch.float16, src_dtype=torch.float32)
              return tmp23
          ,
          ranges=[1, 64, 64, 96],
          origin_node=convert_element_type_1,
          origins={convert_element_type_1, add_3, add_2, mul_2, var_mea...
        ))
      ),
      size=[4096, 96],
      reindex=lambda i0, i1: [0, ModularIndexing(i0, 64, 64), ModularIndexing(i0, 1, 64), i1],
      origins={convert_element_type_1, add_3, add_2, mul_2, var_mea...
    )
  )
  args[1]: TensorBox(
    ReinterpretView(
      StorageBox(
        InputBuffer(name='arg84_1', layout=FixedLayout('cuda', torch.float16, size=[384, 96], stride=[96, 1]))
      ),
      FixedLayout('cuda', torch.float16, size=[96, 384], stride=[1, 96]),
      origins={permute_1}
    )
  )

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```
Following the hit of torch,   after adding  ```torch._dynamo.config.suppress_errors = True```, it works for me( except for  some verbose logs).
```
W0712 09:40:47.552000 140191472064320 torch/_dynamo/convert_frame.py:824] WON'T CONVERT forward /data2/fengfusen/project/LivePortrait/src/modules/stitching_retargeting_network.py line 37 
......
W0712 09:40:47.552000 140191472064320 torch/_dynamo/convert_frame.py:824] Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
W0712 09:40:47.552000 140191472064320 torch/_dynamo/convert_frame.py:824] 
Warm up end!
Number of parameters for Appearance Feature Extractor: 0.84 M
Number of parameters for Motion Extractor: 28.12 M
Number of parameters for Warping Network: 45.53 M
Number of parameters for SPADE Decoder: 55.37 M
Number of parameters for part_0 in Stitching and Retargeting Modules: 0.05 M
Number of parameters for part_1 in Stitching and Retargeting Modules: 0.14 M
Number of parameters for part_2 in Stitching and Retargeting Modules: 0.04 M
Average inference time for Appearance Feature Extractor over 100 runs: 2.12 ms (std: 0.04 ms)
Average inference time for Motion Extractor over 100 runs: 14.23 ms (std: 0.40 ms)
Average inference time for Warping Network over 100 runs: 12.43 ms (std: 0.02 ms)
Average inference time for SPADE Decoder over 100 runs: 12.38 ms (std: 0.03 ms)
Average inference time for Retargeting Models over 100 runs: 0.80 ms (std: 0.09 ms)
```
I'm running on V100 with torch 2.3.0, maybe some bugs with ```torch.compile```.
Hope it's helpful.

**Comment by zzzweakman** [comment]
We have tested it on a V100 device and indeed arrived at the same conclusion as you. Thank you! @iloveOREO

**Pull request merged**
