### PR TITLE
Add a video file as the source input 

### PR DESCRIPTION
**Pull request by ymuhong**
Adding support for inputing a source video file instead of an image:

Example:
<video src="https://github.com/user-attachments/assets/e10a2295-776d-4903-826d-54255c643bb0" controls />

```bash
python inference.py -s assets/examples/driving/d0.mp4 -d assets/examples/driving/d3.mp4  --no-flag-do-crop --no-flag-do-rot
```

### CODE REVIEW

**Comment by Inferencer** [comment]
While this appears to be a community implementation it is interesting to see where it fails and where it works as clearly the teeth are the correct teeth regardless of the starting frame having a closed mouth mentioned here https://github.com/KwaiVGI/LivePortrait/issues/114#issuecomment-2223871917

**Comment by frankjiang** [comment]
Bravo! I'm doing exactly the same work like you are doing.

**Comment by Inferencer** [comment]
can you do just the mouth?

**Comment by x4080** [comment]
Hi, it works perfectly for square source video, but if the source is for example portrait aspect ratio, it will be squeezed into square aspect ratio, is there any settings to fix it ?

**Comment by x4080** [comment]
@ymuhong, here's the fix for the aspect ratio :
@live_portrait_pipeline.py
```
        ######## process source portrait ########
        if is_video(args.source_image):
            source_rgb_lst = load_driving_info(args.source_image)
            source_fps = int(get_fps(args.source_image))
        else:
            img_rgb = load_image_rgb(args.source_image)
            img_rgb = resize_to_limit(img_rgb, inf_cfg.source_max_dim, inf_cfg.source_division)
            source_rgb_lst = [img_rgb]
            source_fps = inf_cfg.output_fps

        # Get source dimensions (add this)
        source_height, source_width = source_rgb_lst[0].shape[:2]
```

then 
```
        for i in track(range(n_frames), description='🚀Animating...', total=n_frames):
            # ... (previous code remains the same)

            out = self.live_portrait_wrapper.warp_decode(f_s, x_s, x_d_i_new)
            I_p_i = self.live_portrait_wrapper.parse_output(out['out'])[0]

            # Resize the output to match source dimensions (add this)
            I_p_i = cv2.resize(I_p_i, (source_width, source_height))

```
Hope it helps

**Comment by ymuhong** [comment]
Thank you @x4080 !
That does seem to fix the output when the source is not 1:1 aspect ratio but its not perfect.
Interestingly, I've tried it on the main repo with an image source and I get the same squeezed results. It seems like the issue stems from using the `--no-flag-do-crop ` flag...

**Comment by ymuhong** [comment]
> can you do just the mouth?

It may be possible.. I've actually been experimenting with controlling the mouth, eyes or head movement individually with varying degrees of success...

https://github.com/user-attachments/assets/2be488a3-326d-467e-a589-7436988d21d3

**Comment by kkhaial** [comment]
I'm getting this issue, tried gradio and terminal, both same thing.

image

**Comment by alexbofa** [comment]
Hello
```
Traceback (most recent call last):
  File "E:\AI-Soft\Portable-LivePortrait\venv\lib\site-packages\gradio\queueing.py", line 541, in process_events
    response = await route_utils.call_process_api(
  File "E:\AI-Soft\Portable-LivePortrait\venv\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\AI-Soft\Portable-LivePortrait\venv\lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "E:\AI-Soft\Portable-LivePortrait\venv\lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI-Soft\Portable-LivePortrait\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\AI-Soft\Portable-LivePortrait\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\AI-Soft\Portable-LivePortrait\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\AI-Soft\Portable-LivePortrait\venv\lib\site-packages\gradio\utils.py", line 833, in wrapper
    response = f(*args, **kwargs)
  File "E:\AI-Soft\Portable-LivePortrait\app.py", line 57, in gpu_wrapped_execute_video
    return gradio_pipeline.execute_video(*args, **kwargs)
  File "E:\AI-Soft\Portable-LivePortrait\src\gradio_pipeline.py", line 65, in execute_video
    video_path, video_path_concat = self.execute(self.args)
  File "E:\AI-Soft\Portable-LivePortrait\src\live_portrait_pipeline.py", line 251, in execute
    frames_concatenated = concat_frames(driving_rgb_crop_256x256_lst, source_img_crop_256, I_p_lst)
  File "E:\AI-Soft\Portable-LivePortrait\src\utils\video.py", line 90, in concat_frames
    source_image_resized = cv2.resize(source_image, (w, h))
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'
```

**Comment by alexbofa** [comment]
Thanks, that's work

**Comment by x4080** [comment]
@ymuhong How do you make the model to only do eyes/mouth movement only ?

**Comment by cleardusk** [comment]
Great thanks for @ymuhong 's PR and inspiration. We have updated an implementation of v2v in the main branch. So I decide to close this PR. Thanks grain : )

**Pull request closed without merging**
