### PR TITLE
doc: Added RunPod template and Docker image

### PR DESCRIPTION
**Pull request by ashleykleynhans**

### CODE REVIEW

**Comment by Inferencer** [comment]
Thank you 🙏

**Comment by cleardusk** [comment]
Thanks for your PR, @ashleykleynhans ! Is RunPod used for commercial purposes?

**Comment by ashleykleynhans** [comment]
> Thanks for your PR, @ashleykleynhans ! Is RunPod used for commercial purposes?

Hi @cleardusk , its a Cloud hosting provider and can be used for personal as well as commercial purposes.  Should I include a link to the license in the README for the template?

**Comment by ashleykleynhans** [comment]
@cleardusk I've changed my Github license to MIT to match this one, and also added notes to the Github repo and RunPod template that the insightface models must be removed for commercial purposes.

**Comment by waguimxxxx** [comment]
Did you remove your template from the run pod?

**Comment by ashleykleynhans** [comment]
Yes, its been removed. I am no longer supporting RunPod because they keep banning me, and this PR has also been sitting here for a month without any progress being made.

**Comment by cleardusk** [comment]
Sorry for the late reply @ashleykleynhans Since we are not very familiar with Runpod, we didn’t address this PR promptly.

If the RunPod template and Docker image is a critical requirement, we will prioritize this task. Could everyone provide some suggestions : )
@ashleykleynhans @Inferencer @waguimxxxx

**Comment by ashleykleynhans** [comment]
You basically just create a docker image and then create a template on RunPod to run that docker image.
In the template configuration, you map the ports.
The container start script should either load the web ui without forking, or alternatively have `sleep infinity` to prevent the container from crash looping.
I can advise someone how to do it but my template has been removed because of my issues with RunPod as described in this thread: https://www.reddit.com/r/StableDiffusion/comments/1emmej6/runpod_and_the_outdated_templates/

**Comment by waguimxxxx** [comment]
I understand, I forked your SD Forge repository, would it be possible for me to create a private template using it? I've already tested several templates and none of them offer an Adetailer like yours, for some reason your template's adetailer function is better than I've seen

**Comment by ashleykleynhans** [comment]
> @ashleykleynhans I don't think you meant to tag me but @waguimxxxx

Yes, my apologies.

**Pull request closed without merging**
